name: Build actions for zipping the lambda function file

on: 
  push:
    branches:
      - main


jobs:
          
  ZipPackagingLambda:
    name: Function deploy
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
        AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
    steps:
      - uses: actions/checkout@v2
      - name: Build code-deploy artifact
        run: |
          zip pack.zip index.py
          ls -al
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Deploy the zip to lambda function
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{secrets.AWS_ACCESS_KEY}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_KEY}}
          aws_region: ${{secrets.AWS_REGION}}
          function_name: verifyEmail
          zip_file: pack.zip