name: Build and deploy

on: 
  push:
    branches:
      - main

jobs:
          
 Deploy-Lambda:
    if: github.repository == 'lareb-neu/serverless '
    name: Function deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build code-deploy artifact
        run: |
          zip bundle.zip sendemail.py
          ls -al
      - name: AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region:  ${{ secrets.AWS_REGION }}
          function_name: verifyEmail
          zip_file: bundle.zip